apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: node-api-app
  name: node-api-app
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: node-api-app
  type: NodePort
status:
  loadBalancer: {}
