apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: node-blog-app
  name: node-blog-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-blog-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: node-blog-app
    spec:
      containers:
      - image: akilan/node-blog:1
        name: node-blog
        resources: {}
status: {}
